export type ItemIds = "acacia_boat" | "amethyst_shard" | "apple" | "armor_stand" | "arrow" | "axolotl_bucket" | "axolotl_spawn_egg" | "baked_potato" | "bat_spawn_egg" | "bee_spawn_egg" | "beef" | "beetroot" | "beetroot_seeds" | "beetroot_soup" | "birch_boat" | "black_dye" | "blaze_powder" | "blaze_rod" | "blaze_spawn_egg" | "blue_dye" | "bone" | "bone_meal" | "book" | "bow" | "bowl" | "bread" | "brick" | "brown_dye" | "bucket" | "bundle" | "carrot" | "carrot_on_a_stick" | "cat_spawn_egg" | "cave_spider_spawn_egg" | "chainmail_boots" | "chainmail_chestplate" | "chainmail_helmet" | "chainmail_leggings" | "charcoal" | "chest_minecart" | "chicken" | "chicken_spawn_egg" | "chorus_fruit" | "clay_ball" | "clock" | "coal" | "cocoa_beans" | "cod" | "cod_bucket" | "cod_spawn_egg" | "command_block_minecart" | "compass" | "cooked_beef" | "cooked_chicken" | "cooked_cod" | "cooked_mutton" | "cooked_porkchop" | "cooked_rabbit" | "cooked_salmon" | "cookie" | "copper_ingot" | "cow_spawn_egg" | "creeper_banner_pattern" | "creeper_spawn_egg" | "crossbow" | "cyan_dye" | "dark_oak_boat" | "debug_stick" | "diamond" | "diamond_axe" | "diamond_boots" | "diamond_chestplate" | "diamond_helmet" | "diamond_hoe" | "diamond_horse_armor" | "diamond_leggings" | "diamond_pickaxe" | "diamond_shovel" | "diamond_sword" | "dolphin_spawn_egg" | "donkey_spawn_egg" | "dragon_breath" | "dried_kelp" | "drowned_spawn_egg" | "egg" | "elder_guardian_spawn_egg" | "elytra" | "emerald" | "enchanted_book" | "enchanted_golden_apple" | "end_crystal" | "ender_eye" | "ender_pearl" | "enderman_spawn_egg" | "endermite_spawn_egg" | "evoker_spawn_egg" | "experience_bottle" | "feather" | "fermented_spider_eye" | "filled_map" | "fire_charge" | "firework_rocket" | "firework_star" | "fishing_rod" | "flint" | "flint_and_steel" | "flower_banner_pattern" | "fox_spawn_egg" | "furnace_minecart" | "ghast_spawn_egg" | "ghast_tear" | "glass_bottle" | "glistering_melon_slice" | "globe_banner_pattern" | "glow_berries" | "glow_ink_sac" | "glow_item_frame" | "glow_squid_spawn_egg" | "glowstone_dust" | "goat_spawn_egg" | "gold_ingot" | "gold_nugget" | "golden_apple" | "golden_axe" | "golden_boots" | "golden_carrot" | "golden_chestplate" | "golden_helmet" | "golden_hoe" | "golden_horse_armor" | "golden_leggings" | "golden_pickaxe" | "golden_shovel" | "golden_sword" | "gray_dye" | "green_dye" | "guardian_spawn_egg" | "gunpowder" | "heart_of_the_sea" | "hoglin_spawn_egg" | "honey_bottle" | "honeycomb" | "hopper_minecart" | "horse_spawn_egg" | "husk_spawn_egg" | "ink_sac" | "iron_axe" | "iron_boots" | "iron_chestplate" | "iron_helmet" | "iron_hoe" | "iron_horse_armor" | "iron_ingot" | "iron_leggings" | "iron_nugget" | "iron_pickaxe" | "iron_shovel" | "iron_sword" | "item_frame" | "jungle_boat" | "knowledge_book" | "lapis_lazuli" | "lava_bucket" | "lead" | "leather" | "leather_boots" | "leather_chestplate" | "leather_helmet" | "leather_horse_armor" | "leather_leggings" | "light_blue_dye" | "light_gray_dye" | "lime_dye" | "lingering_potion" | "llama_spawn_egg" | "magenta_dye" | "magma_cream" | "magma_cube_spawn_egg" | "map" | "melon_seeds" | "melon_slice" | "milk_bucket" | "minecart" | "mojang_banner_pattern" | "mooshroom_spawn_egg" | "mule_spawn_egg" | "mushroom_stew" | "music_disc_11" | "music_disc_13" | "music_disc_blocks" | "music_disc_cat" | "music_disc_chirp" | "music_disc_far" | "music_disc_mall" | "music_disc_mellohi" | "music_disc_pigstep" | "music_disc_stal" | "music_disc_strad" | "music_disc_wait" | "music_disc_ward" | "mutton" | "name_tag" | "nautilus_shell" | "nether_brick" | "nether_star" | "nether_wart" | "netherite_axe" | "netherite_boots" | "netherite_chestplate" | "netherite_helmet" | "netherite_hoe" | "netherite_ingot" | "netherite_leggings" | "netherite_pickaxe" | "netherite_scrap" | "netherite_shovel" | "netherite_sword" | "oak_boat" | "ocelot_spawn_egg" | "orange_dye" | "painting" | "panda_spawn_egg" | "paper" | "parrot_spawn_egg" | "phantom_membrane" | "phantom_spawn_egg" | "pig_spawn_egg" | "piglin_banner_pattern" | "piglin_brute_spawn_egg" | "piglin_spawn_egg" | "pillager_spawn_egg" | "pink_dye" | "poisonous_potato" | "polar_bear_spawn_egg" | "popped_chorus_fruit" | "porkchop" | "potato" | "potion" | "powder_snow_bucket" | "prismarine_crystals" | "prismarine_shard" | "pufferfish" | "pufferfish_bucket" | "pufferfish_spawn_egg" | "pumpkin_pie" | "pumpkin_seeds" | "purple_dye" | "quartz" | "rabbit" | "rabbit_foot" | "rabbit_hide" | "rabbit_spawn_egg" | "rabbit_stew" | "ravager_spawn_egg" | "raw_copper" | "raw_gold" | "raw_iron" | "red_dye" | "redstone" | "rotten_flesh" | "saddle" | "salmon" | "salmon_bucket" | "salmon_spawn_egg" | "scute" | "shears" | "sheep_spawn_egg" | "shield" | "shulker_shell" | "shulker_spawn_egg" | "silverfish_spawn_egg" | "skeleton_horse_spawn_egg" | "skeleton_spawn_egg" | "skull_banner_pattern" | "slime_ball" | "slime_spawn_egg" | "snowball" | "spectral_arrow" | "spider_eye" | "spider_spawn_egg" | "splash_potion" | "spruce_boat" | "spyglass" | "squid_spawn_egg" | "stick" | "stone_axe" | "stone_hoe" | "stone_pickaxe" | "stone_shovel" | "stone_sword" | "stray_spawn_egg" | "strider_spawn_egg" | "string" | "sugar" | "suspicious_stew" | "sweet_berries" | "tipped_arrow" | "tnt_minecart" | "totem_of_undying" | "trader_llama_spawn_egg" | "trident" | "tropical_fish" | "tropical_fish_bucket" | "tropical_fish_spawn_egg" | "turtle_helmet" | "turtle_spawn_egg" | "vex_spawn_egg" | "villager_spawn_egg" | "vindicator_spawn_egg" | "wandering_trader_spawn_egg" | "warped_fungus_on_a_stick" | "water_bucket" | "wheat" | "wheat_seeds" | "white_dye" | "witch_spawn_egg" | "wither_skeleton_spawn_egg" | "wolf_spawn_egg" | "wooden_axe" | "wooden_hoe" | "wooden_pickaxe" | "wooden_shovel" | "wooden_sword" | "writable_book" | "written_book" | "yellow_dye" | "zoglin_spawn_egg" | "zombie_horse_spawn_egg" | "zombie_spawn_egg" | "zombie_villager_spawn_egg" | "zombified_piglin_spawn_egg";
export const ItemTypeArray: ItemIds[] = ["acacia_boat", "amethyst_shard", "apple", "armor_stand", "arrow", "axolotl_bucket", "axolotl_spawn_egg", "baked_potato", "bat_spawn_egg", "bee_spawn_egg", "beef", "beetroot", "beetroot_seeds", "beetroot_soup", "birch_boat", "black_dye", "blaze_powder", "blaze_rod", "blaze_spawn_egg", "blue_dye", "bone", "bone_meal", "book", "bow", "bowl", "bread", "brick", "brown_dye", "bucket", "bundle", "carrot", "carrot_on_a_stick", "cat_spawn_egg", "cave_spider_spawn_egg", "chainmail_boots", "chainmail_chestplate", "chainmail_helmet", "chainmail_leggings", "charcoal", "chest_minecart", "chicken", "chicken_spawn_egg", "chorus_fruit", "clay_ball", "clock", "coal", "cocoa_beans", "cod", "cod_bucket", "cod_spawn_egg", "command_block_minecart", "compass", "cooked_beef", "cooked_chicken", "cooked_cod", "cooked_mutton", "cooked_porkchop", "cooked_rabbit", "cooked_salmon", "cookie", "copper_ingot", "cow_spawn_egg", "creeper_banner_pattern", "creeper_spawn_egg", "crossbow", "cyan_dye", "dark_oak_boat", "debug_stick", "diamond", "diamond_axe", "diamond_boots", "diamond_chestplate", "diamond_helmet", "diamond_hoe", "diamond_horse_armor", "diamond_leggings", "diamond_pickaxe", "diamond_shovel", "diamond_sword", "dolphin_spawn_egg", "donkey_spawn_egg", "dragon_breath", "dried_kelp", "drowned_spawn_egg", "egg", "elder_guardian_spawn_egg", "elytra", "emerald", "enchanted_book", "enchanted_golden_apple", "end_crystal", "ender_eye", "ender_pearl", "enderman_spawn_egg", "endermite_spawn_egg", "evoker_spawn_egg", "experience_bottle", "feather", "fermented_spider_eye", "filled_map", "fire_charge", "firework_rocket", "firework_star", "fishing_rod", "flint", "flint_and_steel", "flower_banner_pattern", "fox_spawn_egg", "furnace_minecart", "ghast_spawn_egg", "ghast_tear", "glass_bottle", "glistering_melon_slice", "globe_banner_pattern", "glow_berries", "glow_ink_sac", "glow_item_frame", "glow_squid_spawn_egg", "glowstone_dust", "goat_spawn_egg", "gold_ingot", "gold_nugget", "golden_apple", "golden_axe", "golden_boots", "golden_carrot", "golden_chestplate", "golden_helmet", "golden_hoe", "golden_horse_armor", "golden_leggings", "golden_pickaxe", "golden_shovel", "golden_sword", "gray_dye", "green_dye", "guardian_spawn_egg", "gunpowder", "heart_of_the_sea", "hoglin_spawn_egg", "honey_bottle", "honeycomb", "hopper_minecart", "horse_spawn_egg", "husk_spawn_egg", "ink_sac", "iron_axe", "iron_boots", "iron_chestplate", "iron_helmet", "iron_hoe", "iron_horse_armor", "iron_ingot", "iron_leggings", "iron_nugget", "iron_pickaxe", "iron_shovel", "iron_sword", "item_frame", "jungle_boat", "knowledge_book", "lapis_lazuli", "lava_bucket", "lead", "leather", "leather_boots", "leather_chestplate", "leather_helmet", "leather_horse_armor", "leather_leggings", "light_blue_dye", "light_gray_dye", "lime_dye", "lingering_potion", "llama_spawn_egg", "magenta_dye", "magma_cream", "magma_cube_spawn_egg", "map", "melon_seeds", "melon_slice", "milk_bucket", "minecart", "mojang_banner_pattern", "mooshroom_spawn_egg", "mule_spawn_egg", "mushroom_stew", "music_disc_11", "music_disc_13", "music_disc_blocks", "music_disc_cat", "music_disc_chirp", "music_disc_far", "music_disc_mall", "music_disc_mellohi", "music_disc_pigstep", "music_disc_stal", "music_disc_strad", "music_disc_wait", "music_disc_ward", "mutton", "name_tag", "nautilus_shell", "nether_brick", "nether_star", "nether_wart", "netherite_axe", "netherite_boots", "netherite_chestplate", "netherite_helmet", "netherite_hoe", "netherite_ingot", "netherite_leggings", "netherite_pickaxe", "netherite_scrap", "netherite_shovel", "netherite_sword", "oak_boat", "ocelot_spawn_egg", "orange_dye", "painting", "panda_spawn_egg", "paper", "parrot_spawn_egg", "phantom_membrane", "phantom_spawn_egg", "pig_spawn_egg", "piglin_banner_pattern", "piglin_brute_spawn_egg", "piglin_spawn_egg", "pillager_spawn_egg", "pink_dye", "poisonous_potato", "polar_bear_spawn_egg", "popped_chorus_fruit", "porkchop", "potato", "potion", "powder_snow_bucket", "prismarine_crystals", "prismarine_shard", "pufferfish", "pufferfish_bucket", "pufferfish_spawn_egg", "pumpkin_pie", "pumpkin_seeds", "purple_dye", "quartz", "rabbit", "rabbit_foot", "rabbit_hide", "rabbit_spawn_egg", "rabbit_stew", "ravager_spawn_egg", "raw_copper", "raw_gold", "raw_iron", "red_dye", "redstone", "rotten_flesh", "saddle", "salmon", "salmon_bucket", "salmon_spawn_egg", "scute", "shears", "sheep_spawn_egg", "shield", "shulker_shell", "shulker_spawn_egg", "silverfish_spawn_egg", "skeleton_horse_spawn_egg", "skeleton_spawn_egg", "skull_banner_pattern", "slime_ball", "slime_spawn_egg", "snowball", "spectral_arrow", "spider_eye", "spider_spawn_egg", "splash_potion", "spruce_boat", "spyglass", "squid_spawn_egg", "stick", "stone_axe", "stone_hoe", "stone_pickaxe", "stone_shovel", "stone_sword", "stray_spawn_egg", "strider_spawn_egg", "string", "sugar", "suspicious_stew", "sweet_berries", "tipped_arrow", "tnt_minecart", "totem_of_undying", "trader_llama_spawn_egg", "trident", "tropical_fish", "tropical_fish_bucket", "tropical_fish_spawn_egg", "turtle_helmet", "turtle_spawn_egg", "vex_spawn_egg", "villager_spawn_egg", "vindicator_spawn_egg", "wandering_trader_spawn_egg", "warped_fungus_on_a_stick", "water_bucket", "wheat", "wheat_seeds", "white_dye", "witch_spawn_egg", "wither_skeleton_spawn_egg", "wolf_spawn_egg", "wooden_axe", "wooden_hoe", "wooden_pickaxe", "wooden_shovel", "wooden_sword", "writable_book", "written_book", "yellow_dye", "zoglin_spawn_egg", "zombie_horse_spawn_egg", "zombie_spawn_egg", "zombie_villager_spawn_egg", "zombified_piglin_spawn_egg"];
export const ItemNames: {[key: string]: string} = {
	"acacia_boat": "Acacia Boat",
	"amethyst_shard": "Amethyst Shard",
	"apple": "Apple",
	"armor_stand": "Armor Stand",
	"arrow": "Arrow",
	"axolotl_bucket": "Bucket of Axolotl",
	"axolotl_spawn_egg": "Axolotl Spawn Egg",
	"baked_potato": "Baked Potato",
	"bat_spawn_egg": "Bat Spawn Egg",
	"bee_spawn_egg": "Bee Spawn Egg",
	"beef": "Raw Beef",
	"beetroot": "Beetroot",
	"beetroot_seeds": "Beetroot Seeds",
	"beetroot_soup": "Beetroot Soup",
	"birch_boat": "Birch Boat",
	"black_dye": "Black Dye",
	"blaze_powder": "Blaze Powder",
	"blaze_rod": "Blaze Rod",
	"blaze_spawn_egg": "Blaze Spawn Egg",
	"blue_dye": "Blue Dye",
	"bone": "Bone",
	"bone_meal": "Bone Meal",
	"book": "Book",
	"bow": "Bow",
	"bowl": "Bowl",
	"bread": "Bread",
	"brick": "Brick",
	"brown_dye": "Brown Dye",
	"bucket": "Bucket",
	"bundle": "Bundle",
	"carrot": "Carrot",
	"carrot_on_a_stick": "Carrot on a Stick",
	"cat_spawn_egg": "Cat Spawn Egg",
	"cave_spider_spawn_egg": "Cave Spider Spawn Egg",
	"chainmail_boots": "Chainmail Boots",
	"chainmail_chestplate": "Chainmail Chestplate",
	"chainmail_helmet": "Chainmail Helmet",
	"chainmail_leggings": "Chainmail Leggings",
	"charcoal": "Charcoal",
	"chest_minecart": "Minecart with Chest",
	"chicken": "Raw Chicken",
	"chicken_spawn_egg": "Chicken Spawn Egg",
	"chorus_fruit": "Chorus Fruit",
	"clay_ball": "Clay Ball",
	"clock": "Clock",
	"coal": "Coal",
	"cocoa_beans": "Cocoa Beans",
	"cod": "Raw Cod",
	"cod_bucket": "Bucket of Cod",
	"cod_spawn_egg": "Cod Spawn Egg",
	"command_block_minecart": "Minecart with Command Block",
	"compass": "Compass",
	"cooked_beef": "Steak",
	"cooked_chicken": "Cooked Chicken",
	"cooked_cod": "Cooked Cod",
	"cooked_mutton": "Cooked Mutton",
	"cooked_porkchop": "Cooked Porkchop",
	"cooked_rabbit": "Cooked Rabbit",
	"cooked_salmon": "Cooked Salmon",
	"cookie": "Cookie",
	"copper_ingot": "Copper Ingot",
	"cow_spawn_egg": "Cow Spawn Egg",
	"creeper_banner_pattern": "Banner Pattern (Creeper Charge)",
	"creeper_spawn_egg": "Creeper Spawn Egg",
	"crossbow": "Crossbow",
	"cyan_dye": "Cyan Dye",
	"dark_oak_boat": "Dark Oak Boat",
	"debug_stick": "Debug Stick",
	"diamond": "Diamond",
	"diamond_axe": "Diamond Axe",
	"diamond_boots": "Diamond Boots",
	"diamond_chestplate": "Diamond Chestplate",
	"diamond_helmet": "Diamond Helmet",
	"diamond_hoe": "Diamond Hoe",
	"diamond_horse_armor": "Diamond Horse Armor",
	"diamond_leggings": "Diamond Leggings",
	"diamond_pickaxe": "Diamond Pickaxe",
	"diamond_shovel": "Diamond Shovel",
	"diamond_sword": "Diamond Sword",
	"dolphin_spawn_egg": "Dolphin Spawn Egg",
	"donkey_spawn_egg": "Donkey Spawn Egg",
	"dragon_breath": "Dragon's Breath",
	"dried_kelp": "Dried Kelp",
	"drowned_spawn_egg": "Drowned Spawn Egg",
	"egg": "Egg",
	"elder_guardian_spawn_egg": "Elder Guardian Spawn Egg",
	"elytra": "Elytra",
	"emerald": "Emerald",
	"enchanted_book": "Enchanted Book",
	"enchanted_golden_apple": "Enchanted Golden Apple",
	"end_crystal": "End Crystal",
	"ender_eye": "Eye of Ender",
	"ender_pearl": "Ender Pearl",
	"enderman_spawn_egg": "Enderman Spawn Egg",
	"endermite_spawn_egg": "Endermite Spawn Egg",
	"evoker_spawn_egg": "Evoker Spawn Egg",
	"experience_bottle": "Bottle o' Enchanting",
	"feather": "Feather",
	"fermented_spider_eye": "Fermented Spider Eye",
	"filled_map": "Map or Explorer Map",
	"fire_charge": "Fire Charge",
	"firework_rocket": "Firework Rocket",
	"firework_star": "Firework Star",
	"fishing_rod": "Fishing Rod",
	"flint": "Flint",
	"flint_and_steel": "Flint and Steel",
	"flower_banner_pattern": "Banner Pattern (Flower Charge)",
	"fox_spawn_egg": "Fox Spawn Egg",
	"furnace_minecart": "Minecart with Furnace",
	"ghast_spawn_egg": "Ghast Spawn Egg",
	"ghast_tear": "Ghast Tear",
	"glass_bottle": "Glass Bottle",
	"glistering_melon_slice": "Glistering Melon Slice",
	"globe_banner_pattern": "Banner Pattern (Globe)",
	"glow_berries": "Glow Berries",
	"glow_ink_sac": "Glow Ink Sac",
	"glow_item_frame": "Glow Item Frame",
	"glow_squid_spawn_egg": "Glow Squid Spawn Egg",
	"glowstone_dust": "Glowstone Dust",
	"goat_spawn_egg": "Goat Spawn Egg",
	"gold_ingot": "Gold Ingot",
	"gold_nugget": "Gold Nugget",
	"golden_apple": "Golden Apple",
	"golden_axe": "Golden Axe",
	"golden_boots": "Golden Boots",
	"golden_carrot": "Golden Carrot",
	"golden_chestplate": "Golden Chestplate",
	"golden_helmet": "Golden Helmet",
	"golden_hoe": "Golden Hoe",
	"golden_horse_armor": "Golden Horse Armor",
	"golden_leggings": "Golden Leggings",
	"golden_pickaxe": "Golden Pickaxe",
	"golden_shovel": "Golden Shovel",
	"golden_sword": "Golden Sword",
	"gray_dye": "Gray Dye",
	"green_dye": "Green Dye",
	"guardian_spawn_egg": "Guardian Spawn Egg",
	"gunpowder": "Gunpowder",
	"heart_of_the_sea": "Heart of the Sea",
	"hoglin_spawn_egg": "Hoglin Spawn Egg",
	"honey_bottle": "Honey Bottle",
	"honeycomb": "Honeycomb",
	"hopper_minecart": "Minecart with Hopper",
	"horse_spawn_egg": "Horse Spawn Egg",
	"husk_spawn_egg": "Husk Spawn Egg",
	"ink_sac": "Ink Sac",
	"iron_axe": "Iron Axe",
	"iron_boots": "Iron Boots",
	"iron_chestplate": "Iron Chestplate",
	"iron_helmet": "Iron Helmet",
	"iron_hoe": "Iron Hoe",
	"iron_horse_armor": "Iron Horse Armor",
	"iron_ingot": "Iron Ingot",
	"iron_leggings": "Iron Leggings",
	"iron_nugget": "Iron Nugget",
	"iron_pickaxe": "Iron Pickaxe",
	"iron_shovel": "Iron Shovel",
	"iron_sword": "Iron Sword",
	"item_frame": "Item Frame",
	"jungle_boat": "Jungle Boat",
	"knowledge_book": "Knowledge Book",
	"lapis_lazuli": "Lapis Lazuli",
	"lava_bucket": "Lava Bucket",
	"lead": "Lead",
	"leather": "Leather",
	"leather_boots": "Leather Boots",
	"leather_chestplate": "Leather Tunic",
	"leather_helmet": "Leather Cap",
	"leather_horse_armor": "Leather Horse Armor",
	"leather_leggings": "Leather Pants",
	"light_blue_dye": "Light Blue Dye",
	"light_gray_dye": "Light Gray Dye",
	"lime_dye": "Lime Dye",
	"lingering_potion": "Lingering Potions",
	"llama_spawn_egg": "Llama Spawn Egg",
	"magenta_dye": "Magenta Dye",
	"magma_cream": "Magma Cream",
	"magma_cube_spawn_egg": "Magma Cube Spawn Egg",
	"map": "Empty Map",
	"melon_seeds": "Melon Seeds",
	"melon_slice": "Melon Slice",
	"milk_bucket": "Milk Bucket",
	"minecart": "Minecart",
	"mojang_banner_pattern": "Banner Pattern (Thing)",
	"mooshroom_spawn_egg": "Mooshroom Spawn Egg",
	"mule_spawn_egg": "Mule Spawn Egg",
	"mushroom_stew": "Mushroom Stew",
	"music_disc_11": "Music Disc (11)",
	"music_disc_13": "Music Disc (13)",
	"music_disc_blocks": "Music Disc (blocks)",
	"music_disc_cat": "Music Disc (cat)",
	"music_disc_chirp": "Music Disc (chirp)",
	"music_disc_far": "Music Disc (far)",
	"music_disc_mall": "Music Disc (mall)",
	"music_disc_mellohi": "Music Disc (mellohi)",
	"music_disc_pigstep": "Music Disc (Pigstep)",
	"music_disc_stal": "Music Disc (stal)",
	"music_disc_strad": "Music Disc (strad)",
	"music_disc_wait": "Music Disc (wait)",
	"music_disc_ward": "Music Disc (ward)",
	"mutton": "Raw Mutton",
	"name_tag": "Name Tag",
	"nautilus_shell": "Nautilus Shell",
	"nether_brick": "Nether Brick",
	"nether_star": "Nether Star",
	"nether_wart": "Nether Wart",
	"netherite_axe": "Netherite Axe",
	"netherite_boots": "Netherite Boots",
	"netherite_chestplate": "Netherite Chestplate",
	"netherite_helmet": "Netherite Helmet",
	"netherite_hoe": "Netherite Hoe",
	"netherite_ingot": "Netherite Ingot",
	"netherite_leggings": "Netherite Leggings",
	"netherite_pickaxe": "Netherite Pickaxe",
	"netherite_scrap": "Netherite Scrap",
	"netherite_shovel": "Netherite Shovel",
	"netherite_sword": "Netherite Sword",
	"oak_boat": "Oak Boat",
	"ocelot_spawn_egg": "Ocelot Spawn Egg",
	"orange_dye": "Orange Dye",
	"painting": "Painting",
	"panda_spawn_egg": "Panda Spawn Egg",
	"paper": "Paper",
	"parrot_spawn_egg": "Parrot Spawn Egg",
	"phantom_membrane": "Phantom Membrane",
	"phantom_spawn_egg": "Phantom Spawn Egg",
	"pig_spawn_egg": "Pig Spawn Egg",
	"piglin_banner_pattern": "Banner Pattern (Snout)",
	"piglin_brute_spawn_egg": "Piglin Brute Spawn Egg",
	"piglin_spawn_egg": "Piglin Spawn Egg",
	"pillager_spawn_egg": "Pillager Spawn Egg",
	"pink_dye": "Pink Dye",
	"poisonous_potato": "Poisonous Potato",
	"polar_bear_spawn_egg": "Polar Bear Spawn Egg",
	"popped_chorus_fruit": "Popped Chorus Fruit",
	"porkchop": "Raw Porkchop",
	"potato": "Potato",
	"potion": "Potions",
	"powder_snow_bucket": "Powder Snow Bucket",
	"prismarine_crystals": "Prismarine Crystals",
	"prismarine_shard": "Prismarine Shard",
	"pufferfish": "Pufferfish",
	"pufferfish_bucket": "Bucket of Pufferfish",
	"pufferfish_spawn_egg": "Pufferfish Spawn Egg",
	"pumpkin_pie": "Pumpkin Pie",
	"pumpkin_seeds": "Pumpkin Seeds",
	"purple_dye": "Purple Dye",
	"quartz": "Nether Quartz",
	"rabbit": "Raw Rabbit",
	"rabbit_foot": "Rabbit's Foot",
	"rabbit_hide": "Rabbit Hide",
	"rabbit_spawn_egg": "Rabbit Spawn Egg",
	"rabbit_stew": "Rabbit Stew",
	"ravager_spawn_egg": "Ravager Spawn Egg",
	"raw_copper": "Raw Copper",
	"raw_gold": "Raw Gold",
	"raw_iron": "Raw Iron",
	"red_dye": "Red Dye",
	"redstone": "Redstone Dust",
	"rotten_flesh": "Rotten Flesh",
	"saddle": "Saddle",
	"salmon": "Raw Salmon",
	"salmon_bucket": "Bucket of Salmon",
	"salmon_spawn_egg": "Salmon Spawn Egg",
	"scute": "Scute",
	"shears": "Shears",
	"sheep_spawn_egg": "Sheep Spawn Egg",
	"shield": "Shield",
	"shulker_shell": "Shulker Shell",
	"shulker_spawn_egg": "Shulker Spawn Egg",
	"silverfish_spawn_egg": "Silverfish Spawn Egg",
	"skeleton_horse_spawn_egg": "Skeleton Horse Spawn Egg",
	"skeleton_spawn_egg": "Skeleton Spawn Egg",
	"skull_banner_pattern": "Banner Pattern (Skull Charge)",
	"slime_ball": "Slimeball",
	"slime_spawn_egg": "Slime Spawn Egg",
	"snowball": "Snowball",
	"spectral_arrow": "Spectral Arrow",
	"spider_eye": "Spider Eye",
	"spider_spawn_egg": "Spider Spawn Egg",
	"splash_potion": "Splash Potions",
	"spruce_boat": "Spruce Boat",
	"spyglass": "Spyglass",
	"squid_spawn_egg": "Squid Spawn Egg",
	"stick": "Stick",
	"stone_axe": "Stone Axe",
	"stone_hoe": "Stone Hoe",
	"stone_pickaxe": "Stone Pickaxe",
	"stone_shovel": "Stone Shovel",
	"stone_sword": "Stone Sword",
	"stray_spawn_egg": "Stray Spawn Egg",
	"strider_spawn_egg": "Strider Spawn Egg",
	"string": "String",
	"sugar": "Sugar",
	"suspicious_stew": "Suspicious Stew",
	"sweet_berries": "Sweet Berries",
	"tipped_arrow": "Tipped Arrows",
	"tnt_minecart": "Minecart with TNT",
	"totem_of_undying": "Totem of Undying",
	"trader_llama_spawn_egg": "Trader Llama Spawn Egg",
	"trident": "Trident",
	"tropical_fish": "Tropical Fish",
	"tropical_fish_bucket": "Bucket of Tropical Fish",
	"tropical_fish_spawn_egg": "Tropical Fish Spawn Egg",
	"turtle_helmet": "Turtle Shell",
	"turtle_spawn_egg": "Turtle Spawn Egg",
	"vex_spawn_egg": "Vex Spawn Egg",
	"villager_spawn_egg": "Villager Spawn Egg",
	"vindicator_spawn_egg": "Vindicator Spawn Egg",
	"wandering_trader_spawn_egg": "Wandering Trader Spawn Egg",
	"warped_fungus_on_a_stick": "Warped Fungus on a Stick",
	"water_bucket": "Water Bucket",
	"wheat": "Wheat",
	"wheat_seeds": "Wheat Seeds",
	"white_dye": "White Dye",
	"witch_spawn_egg": "Witch Spawn Egg",
	"wither_skeleton_spawn_egg": "Wither Skeleton Spawn Egg",
	"wolf_spawn_egg": "Wolf Spawn Egg",
	"wooden_axe": "Wooden Axe",
	"wooden_hoe": "Wooden Hoe",
	"wooden_pickaxe": "Wooden Pickaxe",
	"wooden_shovel": "Wooden Shovel",
	"wooden_sword": "Wooden Sword",
	"writable_book": "Book and Quill",
	"written_book": "Written Book",
	"yellow_dye": "Yellow Dye",
	"zoglin_spawn_egg": "Zoglin Spawn Egg",
	"zombie_horse_spawn_egg": "Zombie Horse Spawn Egg",
	"zombie_spawn_egg": "Zombie Spawn Egg",
	"zombie_villager_spawn_egg": "Zombie Villager Spawn Egg",
	"zombified_piglin_spawn_egg": "Zombified Piglin Spawn Egg"
};
